WITH NOT_CANCEL AS (
    SELECT A.APNT_YMD,
           A.APNT_NO,
           A.PT_NO,
           A.MCDP_CD,
           A.MDDR_ID,
           D.DR_NAME
    FROM APPOINTMENT A JOIN DOCTOR D ON A.MDDR_ID=D.DR_ID
    WHERE 1=1 
        AND
        A.APNT_CNCL_YN = 'N'
        AND
        A.APNT_YMD LIKE '2022-04-13%')
        
SELECT NC.APNT_NO, P.PT_NAME, NC.PT_NO, NC.MCDP_CD, NC.DR_NAME, NC.APNT_YMD
FROM NOT_CANCEL NC JOIN PATIENT P ON NC.PT_NO = P.PT_NO
ORDER BY NC.APNT_YMD