WITH RECURSIVE RC AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM RC
    WHERE HOUR < 23
)

SELECT RC.HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM RC
LEFT JOIN ANIMAL_OUTS A ON RC.HOUR = HOUR(A.DATETIME)
GROUP BY RC.HOUR
ORDER BY 1