SELECT MEMBER_NAME,
       REVIEW_TEXT,
       DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM
    MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM (
            SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(*) DESC) RNK
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
             ) SUB
    WHERE RNK = 1
    )
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC;