# 2022년 1월의 카테고리 별 도서 판매량을 합산(필요컬럼: CATEGORY / SALES_DATE / SALES)
#카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
# 결과는 카테고리명을 기준으로 오름차순 정렬

SELECT B.CATEGORY CATEGORY,
       SUM(S.SALES) TOTAL_SALES
FROM BOOK B INNER JOIN BOOK_SALES S ON B.BOOK_ID=S.BOOK_ID
WHERE MONTH(S.SALES_DATE)='1'
GROUP BY B.CATEGORY
ORDER BY 1